name: CI Pipeline for Python Hello World

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"  # Adjust the version as needed

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Lint with Flake8
    - name: Lint Code with Flake8
      run: |
        python -m pip install flake8
        flake8 --max-line-length=88 .

    # Step 5: Run tests
    - name: Run Tests
      run: pytest

    # Step 6: Snyk Security Scan
    - name: Snyk Dependency Security Scan
      uses: snyk/actions/python@v1
      with:
        args: test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # # Step 7: SonarQube Static Analysis
    # - name: SonarQube Scan
    #   uses: sonarsource/sonarcloud-github-action@v1
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   with:
    #     projectBaseDir: .
    #     args: >
    #       -Dsonar.projectKey=YOUR_PROJECT_KEY
    #       -Dsonar.organization=YOUR_ORGANIZATION_KEY
    #       -Dsonar.host.url=https://sonarcloud.io
